# Generated by Django 6.0.2 on 2026-02-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsApp', '0002_remove_userforms_user_form_formresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='allow_excel_download',
            field=models.BooleanField(default=True, help_text='Allow admins to download form responses as Excel'),
        ),
    ]
